language: en_US

# ################################ #
#                                  #
#         Private Region           #
# ################################ #
private-region:
  # The number limit of Private Regions per person could have
  # One who has "kingdom.admin" permissions will not be limited by this option.
  amount-limit: 1

  # The names of the world in which the private regions are effective.
  allow-worlds:
    - world

  # If true, players will not be able to break or place outside their Private Regions.
  ban-breaking: true

  claim:
    # The limit of claiming chunks for Private Region
    limit: 8
    core-block: BEACON

  # The default currency used to operate the region.
  default-currency: default

#Teleport Setting
teleport:
  #"per" block's distance between two regions' "cost"
  per: 500
  cost: 1
  #The extra cost of trans-world teleporting.
  world: 1
  item:
    material: DYE
    name: "§a§lRegion Stone"
    lore:
      - "§cThe stone has some special space energy inside."
      - "§cConsequently,it's used to teleport."